### ISSUE TITLE
Best Practices for Development and Production Releases

### ISSUE THREAD

**Issue by Exadra37** [exadra37-versioning/explicit-versioning#4]
Due to [this comment](https://github.com/exadra37-versioning/explicit-versioning/pull/2#discussion_r113977252) it will be good to create a separated documentation file with examples how to use Explicit Versioning for Development releases and Production Releases.

Maybe something like `how-to-use.md` file should then be linked from the Specification in the README.

**Comment by colomet** [comment]
if we need to create a how to use file, we are making the system too complicate

**Comment by Exadra37** [comment]
The how to use is just to recommend best practices in using it and is in a separated file with exactly the purpose of not cluttering the README that must be only related with establishing the specifications.

And maybe a better title would be `best-pratices.md`.

**Comment by colomet** [comment]
@Exadra37 you mean https://software-development-guidelines.github.io/CMSver/VERSIONING.html
(under development)

**Comment by Exadra37** [comment]
@colomet 

No that is not what I have in mind.

I will describe best practices for versioning when:

* we start Development in a repository from scratch `0.0.0.0` until it becomes Production ready `1.0.0.0`.
* we need to versioning for Development after `1.0.0.0`.
* we need to tag a new release.

**Comment by sapioit** [comment]
In other words, practical examples of it's usage, to maximize the percentage of readers that/who completely gasp the concept.

**Comment by Exadra37** [comment]
I will try to outline the best practices to use Explicit Versioning in several stages of the life cycle of Software Development.

Some people hate to read or just read in the diagonal and then start posting questions that clearly show they have not payed attention to what they were reading.

This type of people learn/grasp better with practical examples and having a guide for Best Practices with some examples will help them and others to completely grasp the concept of Explicit Versioning as you @sapioit wisely have said ;)
