### ISSUE TITLE
Improve Required Identifiers Schema

### ISSUE THREAD

**Issue by Exadra37** [exadra37-versioning/explicit-versioning#8]
>Release
>   is incremented when changing the API, changing the UX, switching to a new recommended version or ending support for previous versions.

When working on issue #4 I realized that the text for the `Release` identifier is somewhat contradictory, due to saying that can be used to release new versions or to end support  for previous versions.

Giving a version `1.0.28.32` that we end support for it means we will tag it as `2.0.0.0`, but for this to happen the functionality MUST have changed a lot, what means we are using a new version.

Putting it in another way if we already have a version `2.*` how you gone increment the version `1.*` to mark is end of support???

Ending support for a previous version should be done using the Optional Identifier, like:

* `1.0.28.32-End_Of_Support`.
* `1.0.28.32-EOS`
* `1.0.28.32-Final`

Also I have found a better naming for the first identifier that will please @colomet 

`Disruptive`.`Incompatible`.`Compatible`.`Fix`

**Comment by colomet** [comment]
Explicit
Option 1 `Disruptive.Incompatible.Compatible.Fix`
@sapioit  suggestion 
Option 2 `Bussiness.Overhaul.Change.Fix`

Implicit (that is implicit? sorry I´m not sure if I understand the terminology)
Option 3 `Macro.Major.Minor.MIcro`

**Comment by colomet** [comment]
I can say option 1 is not bad at all. I will ask to my team

**Comment by sapioit** [comment]
Indeed, [`Disruptive`](http://www.dictionary.com/browse/disruptive) seems like a good word to express it's point.
And yes, using optional identifiers to end support is a good way to do it.
